# CI/CD pipeline. 

name: CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

  pull_request:
  push:
    branches:
      - "main"
env:
  CI: true

jobs:
  version:
    name: Create a version number
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      number: ${{ steps.pick_version_number.outputs.version }}

    steps:
    - uses: actions/checkout@v2

    - name: Create version number
      id: create_version_number
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: main,master
        PRERELEASE_SUFFIX: pre

    - name: Pick version number
      id: pick_version_number
      run: |
        VALID_VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9](-[A-Za-z0-9]+)?$"

        if [ ! -z "${MANUAL_VERSION}" ] ; then
          echo "User supplied version: ${MANUAL_VERSION}"

          VERSION="${MANUAL_VERSION}"
        elif [ ! -z "${TAG_VERSION}" ] ; then
          echo "Tag bump generated version: ${TAG_VERSION}"

          VERSION="${TAG_VERSION/-pre\./-pre}"
        else
          echo "Neither manual or tag version set"
          exit 1
        fi

        if [[ ${VERSION} =~ ${VALID_VERSION_REGEX} ]] && [ "${VERSION}" != "v0.0.0" ] ; then
          echo "Version number is valid: ${VERSION}"
          echo "::set-output name=version::${VERSION}"
        else
          echo "Version number is not valid ${VERSION}"
          exit 1
        fi

      env:
        TAG_VERSION: ${{ steps.create_version_number.outputs.new_tag }}
        MANUAL_VERSION: ${{ github.event.inputs.version }}

    - name: Echo version number
      run: echo ${{ steps.pick_version_number.outputs.version }}

  build:
    name: Build .NET executable
    runs-on: ubuntu-latest
    container: ghul/devcontainer:dotnet
    timeout-minutes: 10
    needs: [version]

    steps:
    - uses: actions/checkout@v2
                    
    - name: Pack
      run: dotnet pack ghul-pipes -p:Version=${{ needs.version.outputs.number }}

    - name: Test
      run: dotnet test tests

    - name: Upload .NET package artefact
      if: ${{ github.event_name != 'push' }}
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ghul-pipes/nupkg

    - name: Publish package to GitHub
      run: dotnet nuget push ./ghul-pipes/nupkg/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/degory/index.json --skip-duplicate --no-symbols true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package to NuGet
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      run: dotnet nuget push ./ghul-pipes/nupkg/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
